version: '3.1'

services:
  mongo:
    image: mongo:4.2.6
    ports:
      - 27017:27017
    expose:
      - '27017'
    networks:
      - network
    volumes:
      - wm_mongo_data:/data/db


  mongo-express:
    image: mongo-express
    networks:
      - network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  wm_mongo_data:

networks:
  network:
